SELECT * FROM EMPLOYEES 
WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS);

SELECT * FROM EMPLOYEES 
WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS 
                WHERE JOB_TITLE = 'Jr. Designer')

SELECT * FROM JOBS
WHERE JOB_IDENT IN (SELECT JOB_ID FROM EMPLOYEES
                    WHERE SALARY > 70000);

SELECT * FROM JOBS
WHERE JOB_IDENT IN (SELECT JOB_ID FROM EMPLOYEES
                    WHERE YEAR(B_DATE) > 1976);

SELECT * FROM JOBS
WHERE JOB_IDENT IN (SELECT JOB_ID FROM EMPLOYEES
                    WHERE YEAR(B_DATE) > 1976 AND SEX = 'F');