SELECT DEP_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEP_ID

SELECT DEP_ID, COUNT(*), AVG(SALARY) 
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) as NUM_EMPLOYEES,  AVG(SALARY) as AVG_SALARY
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) as NUM_EMPLOYEES,  AVG(SALARY) as AVG_SALARY
FROM EMPLOYEES
GROUP BY DEP_ID
ORDER BY AVG_SALARY;

SELECT DEP_ID, COUNT(*) as NUM_EMPLOYEES,  AVG(SALARY) as AVG_SALARY
FROM EMPLOYEES
GROUP BY DEP_ID HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;

SELECT DEP_ID, COUNT(*) as NUM_EMPLOYEES,  AVG(SALARY) as AVG_SALARY
FROM EMPLOYEES
GROUP BY DEP_ID HAVING NUM_EMPLOYEES < 4
ORDER BY AVG_SALARY;